### PR TITLE
[ENH] Improved discord_rpc

### PR DESCRIPTION
**Pull request by lm41**
What is planned:

- [x] Album name when hovering above the cover
- [x] Display the elapsed track time.
- [x] Added the two above also for episodes
- [x] Display the current playing status using the `smallImageKey`
- [ ] More Ideas?

### CODE REVIEW

**Comment by duzda** [comment]
Hello, 

this.player.getPosition(), should be in micros (seconds * 1 000 000),  however as noted in the comment, it's kinda hacky solution, might be okay for Discord, but for more precise results, you would have to send the position from renderer (mpris_renderer.js -> ipc_handler.js)

You probably wanna somehow change the endTimeStamp on pause, stop and other events.

Also I noticed you're accessing this.player.getPosition, instead of this.player.getPosition() <-- Missing bracelets. Feel free to view the code review code I left.

While you're at it, I think it would make sense to add this feature to podcasts as well, but leave it as the last thing in your todos (it's basically copy pasting, but using 'EPISODE_TITLE' instead of 'ALB_TITLE' etc.).

**Comment by lm41** [comment]
Hello,

thank you for the explanation.

> this.player.getPosition(), should be in micros (seconds * 1 000 000), however as noted in the comment, it's kinda hacky solution, might be okay for Discord, but for more precise results, you would have to send the position from renderer (mpris_renderer.js -> ipc_handler.js).

Any idea how this could work?

> You probably wanna somehow change the endTimeStamp on pause, stop and other events.

It is actually only displayed if the player is not paused. I don't know how and why, but in my opinion that's the way to do it. If it is paused it won't display the time at all.

> While you're at it, I think it would make sense to add this feature to podcasts as well, but leave it as the last thing in your todos (it's basically copy pasting, but using 'EPISODE_TITLE' instead of 'ALB_TITLE' etc.).

I had hat in mind ;-)

**Comment by duzda** [comment]
> > this.player.getPosition(), should be in micros (seconds * 1 000 000), however as noted in the comment, it's kinda hacky solution, might be okay for Discord, but for more precise results, you would have to send the position from renderer (mpris_renderer.js -> ipc_handler.js).
> 
> Any idea how this could work?

I just realized how complicated this solution would be, you would have to ping-pong between processes, which is ridiculously complicated, to just obtain the position. Also the solution would be async, which is usually problematic. Keep it as it's as it's much more readable and maintainable, just beware, this.player.getPosition() sometimes returns NaN, because this.songOffset is uninitialized, which might cause some problems?

Glad you do not have to worry about the other things I mentioned or you've already implemented them, good job!

Let me know whether there is something more to add or this branch is ready for testing.

**Comment by lm41** [comment]
Ready for testing now :-)

**Comment by lm41** [comment]
Also is there a reason whx tracs are sometimes loading so long? Like 10 to 15 seconds?

**Comment by duzda** [comment]
> Also is there a reason whx tracs are sometimes loading so long? Like 10 to 15 seconds?

Shouldn't be happening, but as far as I know this is probably Deezer issue.

**Comment by duzda** [comment]
> Ready for testing now :-)

Most is looking good, although the time is kinda buggy, currently looking into it, but it will take probably some time...

Also, wouldn't it just make sense to instead of how much time's left show current time and total time (maybe remaining time)?

**Comment by lm41** [comment]
The Discord RPC API has only two time values. One can be set and from this time the rpc is counting up. The other is set to a time in the future and it is counting down to this time.

**Comment by duzda** [comment]
I see, I think we should instead use the elapsed time. 

I've added a commit that cleans up the code base a bit and fixes some problems, as well as uses elapsed time instead of remaining.

Lastly, could you please comment, where you got the play/pause images and their license? I'm still thinking where to put these two images, but it probably won't be the assets folder, as assets folder is basically for file system stuff, that can't be stored elsewhere and these are stored via web.

**Comment by duzda** [comment]
And of course, try it out!

**Comment by lm41** [comment]
https://fonts.google.com/icons?selected=Material+Icons+Round:play_circle:
https://fonts.google.com/icons?selected=Material+Icons+Round:pause_circle:
https://github.com/google/material-design-icons#license

**Comment by duzda** [comment]
Hey, just to let you know, I've been super busy lately, I will surely add this to the next version once I have a little bit more time, this will hopefully be in a two weeks or so!

**Pull request merged**
