### PR TITLE
redesigned icon, provided svg icon(not yet implemented)

### PR DESCRIPTION
**Pull request by fischer-felix**
I just thought the squared off icon looked kind of ugly, so I made a rounded one as an svg and png. Currently, only the png is implemented, but the svg is now also located in the assets/ folder.

### CODE REVIEW

**Comment by fischer-felix** [comment]
You could possibly provide the icons by placing them in a folder like /usr/share/pixmaps and then updating the deezer-enhanced.desktop file with the matching icon (i.e round, square, or any other formfactor you like).

**Comment by fischer-felix** [comment]
I am now implementing a new checkbox in the settings page to use the rounded icon, but I can't figure out where the text for the entries and descriptions is styled, so it currently looks like this:
Screenshot_20211029_224651

**Comment by fischer-felix** [comment]
Also, would any modifications to the install be necessary to also provide the round icon (to /usr/shar/icons/hicolor/XxX/apps)?

**Comment by duzda** [comment]
I was thinking of implementing this feature in the install script only as otherwise you need to ask for sudo privileges, which doesn't seem nice. Also, it's unnecessary to store multiple icons, if you only use one set anyways. But you may know better than me, I'm not much of an icons user.

Changing the desktop file means, that the icon in the title bar (not sure) will stay the same, as well as the tray icon. Which you may, or may not be interested in changing, otherwise I think it's good solution.

Yes, I think it's necessary to provide icons to /usr/shar/icons/hicolor/XxX/apps but I'm not 100 % sure, so see for yourself.

**Comment by duzda** [comment]
Also, if you anyways decide to implement this into the settings, do not worry about all the labels and so on, I can later implement it myself once rest of the functionality is fine.

**Comment by duzda** [comment]
Don't worry about the conflicts, I can resolve them myself later, just moved a few files.

**Comment by fischer-felix** [comment]
I think I have a finalized version now, I work around needing root access by copying the dektop file to .local/share/applications and wget the round icon to .local/share/icons/... if needed. If the user wants to change icons, I simply update deezer-enhanced.desktop using sed. 
I added sed and wget as dependencies in the PKGBUILD files, if dependencies need to be specified in any other places, than that still needs to be done.
Apart from that, I hope I accounted for most scenarios (at least the ones I could test).

**Comment by duzda** [comment]
Hey, this solution looks really crazy, I'll still have to consider how most apps do it and whether there isn't any better, cleaner solution that slipped our minds. Nevertheless, hopefully this feature will get merged one way or the other by the end of this week.

**Comment by duzda** [comment]
Alright, so after taking a closer look onto how exactly does it work and testing it myself, I don't think this is something we really wanna do, also it looks like a nightmare to debug. Most apps just provide some default icon and that's it, I would prefer to stick to this and leave the icon as it is. 

On the other hand, the app uses tray and the tray icon can't be switched as easily as the desktop icon, that means the priority should be to use the desktop icon as tray icon, which honestly I'm not sure whether electron supports.

Sadly, all of this means I will have to close this PR, although I'm open to creating a new repo that would contain alternative icons and an install script if that's suitable.

**Comment by duzda** [comment]
Nevermind, once again I was wrong! You can now easily change the tray icon, it's located in /opt/Deezer Enhanced/resources/assets/icon.png which is not the best location, but it works. Check out the dev branch.

**Pull request closed without merging**
